version: '3.8'

services:
  photo-web:
    container_name: photo-web2
    image: photo-web2
    build:
      context: ./photo-store-web
    volumes:
      - ./photo-store-web:/app
      - /app/node_modules
    ports:
      - 3000:3000
    expose:
      - 3000
    command: npm start
    networks:
      - webnet
    links:
      - photo-app

  photo-app:
    container_name: photo-app2
    image: photo-app2
    build:
      context: ./photo-store-application
    volumes:
      - ./photo-store-application:/app
      - /app/node_modules
    ports:
      - 3001:3001
    expose:
      - 3001
    command: npm run start:dev
    networks:
      - webnet
    links:
      - photo-server

  photo-server:
    container_name: photo-server2
    image: photo-server2
    build:
      context: ./photo-store-service
    volumes:
      - ./photo-store-service:/app
      - /app/node_modules
    ports:
      - 3002:3002
    command: npm run start:dev
    networks:
      - webnet

networks:
  webnet:

volumes:
  pgdata: