version: '3.8'

services:
  photo-app:
    container_name: photo-app1
    image: photo-app1
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    networks:
      - webnet
networks:
  webnet:
volumes:
  pgdata: